### ISSUE TITLE
Tuist 기본 작업

### ISSUE THREAD

**Issue by JungDohyeon** [zani-app/ZANI-iOS#1]
## 🚀 Description
> Tuist와 관련한 모듈 및 기본 프로젝트 셋팅 작업을 진행합니다.
<br>

## ✅ TODO
- [x] 모듈 분리
- [x] Tuist 기본 설정
- [x] 기본 프로젝트 설정
- [x] 외부 패키지 설정
<br>

### 📌 ETC
> 기타 참고 사항을 적어주세요 (Optional)
