### ISSUE TITLE
[ZNI-17] 밤샘 탭 UI 제작

### ISSUE THREAD

**Issue by JungDohyeon** [zani-app/ZANI-iOS#12]
## 🚀 Description
> 밤샘 탭 유저 플로우 UI를 그립니다.
<br>

## ✅ TODO
- [x] 밤샘 팀이 없는 경우 Main UI [ZNI-18]
- [ ] 밤샘 미션 타임라인 UI [ZNI-19]
- [ ] 밤샘 팀 멤버 UI [ZNI-20]
- [x] 밤샘 팀이 있는 경우 Main UI [ZNI-21]
<br>

### 📌 ETC
> 기타 참고 사항을 적어주세요 (Optional)

[ZNI-18]: https://zani.atlassian.net/browse/ZNI-18?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ZNI-19]: https://zani.atlassian.net/browse/ZNI-19?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ZNI-20]: https://zani.atlassian.net/browse/ZNI-20?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ZNI-21]: https://zani.atlassian.net/browse/ZNI-21?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
